### ISSUE TITLE
Bystander name

### ISSUE THREAD

**Issue by DropMotion** [mechanicalmind/murder#25]
I change the names of the players in : sv_bystandername.lua
When someone talks (with the microphone) or in the HUD there in writing Bystander.

**Comment by Herover** [comment]
It fixed itself for me after updating the server.

**Comment by DropMotion** [comment]
don't work :/

**Comment by Herover** [comment]
Try post your sv_bystandername.lua file here

**Comment by DropMotion** [comment]
GM.BystanderNameParts = {"Patrick Sebastien",
"Shlouktouftouf",
"Charlie",
"Grille pain",
"Four à petites ondes",
"Mon prenom est trop profond pour toi",
"Vous ne passerez pas",
"Si je passerais",
"Le trou est trop petit",
"La prise USB ne passe pas",
"Si tu vois mon pseudo, tu es déjà mort",
"Lima masse",
"Le roux",
"La poule",
"Oscar",
"Monster munch",
"Quebec quoi",
"Scarface du ghetto",
"Abdoul Keder",
"Mimidou du radiateur",
"Jean Bernard Papi",
"Le coréen",
"Bouboule",
"Jean mi du 13",
"Kevin du phalempins",
"Poile de carotte"
}

local PlayerMeta = FindMetaTable("Player")
local EntityMeta = FindMetaTable("Entity")

GM.BystanderWords = CreateClientConVar( "mu_bystandername_words", 1, FCVAR_ARCHIVE, "Number of words to generate for bystander name" )

// adds a name to the bystander parts generation table
function GM:AddBystanderNamePart(name)
	table.insert(self.BystanderNameParts, name)
end

// removes a name to the bystander parts generation table
function GM:RemoveBystanderNamePart(name)
	table.RemoveByValue(self.BystanderNameParts, name)
end

// returns the bystander parts generation table
function GM:GetBystanderNameParts()
	return self.BystanderNameParts
end

function GM:GenerateName(words)
	if #self.BystanderNameParts <= 0 then
		return "error"
	end
	local name
	for i = 1, words do
		local word = self.BystanderNameParts[math.random(#self.BystanderNameParts)]
		if !name then
			name = word
		else
			name = name .. " " .. word
		end
	end
	return name
end

function GM:LoadBystanderNames()
	local jason = file.ReadDataAndContent("murder/bystander_name_parts.txt")
	if jason then
		local tbl = {}
		local i = 1
		for name in jason:gmatch("[^\r\n]+") do
			table.insert(tbl, name)
		end
		self.BystanderNameParts = tbl
	end
end

function EntityMeta:GenerateBystanderName()
	local words = math.max(1, GAMEMODE.BystanderWords:GetInt())
	local name = GAMEMODE:GenerateName(words)
	self:SetNWString("bystanderName", name)
	self.BystanderName = name
end

function EntityMeta:SetBystanderName(name)
	self:SetNWString("bystanderName", name)
	self.BystanderName = name
end

function EntityMeta:GetBystanderName()
	local name = self:GetNWString("bystanderName")
	if !name || name == "" then
		return "Bystander" 
	end
	return name
end

concommand.Add("mu_print_players", function (admin, com, args)
	if !admin:IsAdmin() then return end

	for k, ply in pairs(player.GetAll()) do
		local c = ChatText()
		c:Add(ply:Nick())
		local col = ply:GetPlayerColor()
		c:Add(" " .. ply:GetBystanderName(), Color(col.x * 255, col.y * 255, col.z * 255))
		c:Add(" " .. ply:SteamID())
		c:Add(" " .. team.GetName(ply:Team()), team.GetColor(ply:Team()))
		c:Send(admin)
	end
end)

**Comment by Herover** [comment]
Nothing I notice :/
You could try play around with mu_bystandername_words and set it to something else than 1.

Also, IIRC mechanicalmind suggested on a workshop thread that people use `GAMEMODE:RemoveBystanderNamePart` and `GAMEMODE:AddBystanderNamePart` instead of editing this file. (Incoming shameless self-advertising) [I made a addon myself which remove all the names and add custom ones](https://github.com/Herover/GModMurderNames/blob/master/murdernames/lua/autorun/server/bystandercountries.lua) using this method.
