### ISSUE TITLE
Magnum and Knife (sometimes) do not appear.

### ISSUE THREAD

**Issue by TNovalis** [MechanicalMind/murder#51]
**Version**: v26

**Problem**: ~25% of the time when the murderer or bystander with a secret weapon pull out their weapon, it is not visible in first person. It is not the most urgent thing as the weapons are still usable but it does make the server feel that it is lower quality.

**Other stuff**: No errors for client or server and screenshots will be provided if requested.

**Comment by Herover** [comment]
As a workaround, you can use the [old code](https://github.com/mechanicalmind/murder/commit/a7849efb54679e77f718756e7a791c9c9211900f#diff-bdfd3483c277e10323f6e682ac77a8c1). I've experienced weapons disappearing there too, but not as often.

**Comment by Reigners** [comment]
Noticed that weapons disappear while picking up something.
Situation : had a knife , was running around and heard a pick up sound (ammo pick up) afterwards knife disappeared.
Situation2 : Magnum was invisible , collected 5 clues and reappeard.

**Comment by MechanicalMind** [comment]
I believe this was fixed in a GMod update. Reopen if not.
