### ISSUE TITLE
Tab

### ISSUE THREAD

**Issue by Reynnox** [mechanicalmind/murder#53]
How we change the color of the scoreboard ? ( In garry's Mod Murder )
Example : yellow for superadmin ; red for admin and blue for modo

**Comment by fixator10** [comment]
Add after this line
https://github.com/mechanicalmind/murder/blob/master/gamemode/cl_scoreboard.lua#L24
this code
```Lua
		elseif ply:IsUserGroup( "group_name_here" )
			surface.SetDrawColor(Color(R,G,B))
```

Replace `group_name_here` with name of a group whose color you want to change.
And then replace `R,G,B` with color that you want change to. Example:
- `255,0,0` - Red
- `0,255,0` - Green
- `0,0,255` - Blue

You can use [any color picker](http://www.colorpicker.com/) to pick R, G, B value

**Comment by Reynnox** [comment]
Like this ? : 

if IsValid(ply) && showAdmins && ply:IsAdmin() then
			surface.SetDrawColor(Color(150,50,50))
		elseif ply:IsUserGroup( "superadmin" )
            surface.SetDrawColor(Color(130,8,8))
		elseif ply:IsUserGroup( "Admin" )
            surface.SetDrawColor(Color(191,10,10))
		elseif ply:IsUserGroup( "Modo" )
            surface.SetDrawColor(Color(10,10,191))
		else
			surface.SetDrawColor(team.GetColor(pteam))
		end
		surface.DrawRect(0, 0, w, h)

		surface.SetDrawColor(255,255,255,10)
		surface.DrawRect(0, 0, w, h * 0.45 )

		surface.SetDrawColor(color_black)
		surface.DrawOutlinedRect(0, 0, w, h)

**Comment by fixator10** [comment]
Yes, i think, but if you want to replace default Red highlighting for admins, i think, you must replace
```Lua
if IsValid(ply) && showAdmins && ply:IsAdmin() then
surface.SetDrawColor(Color(150,50,50))
elseif ply:IsUserGroup( "superadmin" ) then
surface.SetDrawColor(Color(130,8,8))
```
with
```Lua
if IsValid(ply) && showAdmins && ply:IsUserGroup( "superadmin" ) then
surface.SetDrawColor(Color(130,8,8))
```

Actually, i think best code in this case is
```Lua
if IsValid(ply) && showAdmins && ply:IsAdmin() then
     surface.SetDrawColor(Color(150,50,50))
elseif IsValid(ply) && showAdmins && ply:IsUserGroup( "superadmin" ) then
     surface.SetDrawColor(Color(130,8,8))
elseif IsValid(ply) && showAdmins && ply:IsUserGroup( "Admin" ) then
     surface.SetDrawColor(Color(191,10,10))
elseif IsValid(ply) && showAdmins && ply:IsUserGroup( "Modo" ) then
     surface.SetDrawColor(Color(10,10,191))
else
     surface.SetDrawColor(team.GetColor(pteam))
end
```

And yeah, if you want to use code that i provided earlier, add `then` (`if condition then`) after each condition, i forgot to add them…

**Comment by fixator10** [comment]
Try [this](https://github.com/fixator10/murder/blob/master/gamemode/cl_scoreboard.lua)

**Comment by Reynnox** [comment]
It doesn't work

**Comment by Reynnox** [comment]
When i write that , Admin and Modo d'ont have color

**Comment by fixator10** [comment]
Try to upload your cl_scoreboard.lua to [gist](https://gist.github.com/) and give me a link

**Comment by Reynnox** [comment]
https://gist.github.com/Reynnox/fbc6f41081b7a035ed9124cf78fb71a3

**Comment by fixator10** [comment]
Try to make `Admin` and `Modo` lowercase. Like an `admin` & `modo`

**Comment by Reynnox** [comment]
ok thx
