### ISSUE TITLE
Move all text files to new `data_static` folder

### ISSUE THREAD

**Issue by FlorianLeChat** [MechanicalMind/murder#88]
Since the last Garry's Mod update, all addons with a `data` folder inside no longer work because these static files have to be moved to a special (read-only) folder called `data_static` and should be moved to the root gamemode directory instead of `content/data`. I've reported this issue to the Garry's Mod developers (https://discord.com/channels/565105920414318602/589120351238225940/1185530854278189106) but it's not a bug and is considered a new behavior. Several gamemodes including [Prophunters](https://github.com/MechanicalMind/prophunters), [Zombie Survival](https://github.com/JetBoom/zombiesurvival/issues/249), [MelonBomber](https://github.com/MechanicalMind/melonbomber/issues/9) and [Morbus](https://github.com/Remscar/Morbus/issues/51) are suffering from the same issue.

Related to: https://github.com/Facepunch/garrysmod-issues/issues/5648

**Comment by MechanicalMind** [comment]
Should be fixed now.
